module.exports = {
  COGNITIVE_SERVICES_SUBSCRIPTION_KEY: process.env.COGNITIVE_SERVICES_SUBSCRIPTION_KEY,
  
  AZURE_STORAGE_ACCESS_KEY: process.env.AZURE_STORAGE_ACCESS_KEY,
  AZURE_STORAGE_ACCOUNT: process.env.AZURE_STORAGE_ACCOUNT
};